name: Github Membership
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - env:
          PYTHONUNBUFFERED: "true"
          PYTHONDONTWRITEBYTECODE: "true"
          X_GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
        run: |
          pip install -r github/requirements.txt
          cd github; python main.py
